### ISSUE TITLE
unable to login: Too Many Requests for url

### ISSUE THREAD

**Issue by december-soul** [mkuthan/garmin-workouts#2]
Hello

I'm not able to login to garmin.
Too Many Requests for url: https://sso.garmin.com/sso/signin

login via firefox works very well.

btw, nice project!

```(garmin-workouts) foo@Z400:~/src/garmin-workouts$ python3 -m garminworkouts -u "bla@gmx.de" -p secret list
INFO:garminworkouts.garmin.garminclient:Authenticate user bla@gmx.de'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../src/garmin-workouts/garminworkouts/__main__.py", line 110, in <module>
    main()
  File ".../src/garmin-workouts/garminworkouts/__main__.py", line 106, in main
    args.func(args)
  File ".../src/garmin-workouts/garminworkouts/__main__.py", line 50, in command_list
    with _garmin_client(args) as connection:
  File ".../src/garmin-workouts/garminworkouts/garmin/garminclient.py", line 29, in __enter__
    self._connect()
  File ".../src/garmin-workouts/garminworkouts/garmin/garminclient.py", line 103, in _connect
    self._authenticate()
  File ".../src/garmin-workouts/garminworkouts/garmin/garminclient.py", line 129, in _authenticate
    auth_response.raise_for_status()
  File ".../.local/share/virtualenvs/garmin-workouts-VBtzPHpF/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://sso.garmin.com/sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern```

**Comment by december-soul** [comment]
wait 1h and now it works

**Comment by mkuthan** [comment]
@december-soul welcome to the project :) 

GarminClient stores session cookies into "cookie jar" into hidden file .garmin-cookies.txt in the current directory. If file exists and contains valid session cookie the authentication is bypassed. If not the authentication request to the SSO site must be sent. Please ensure that you call the tool from the same directory to avoid too many authentication requests.
