### ISSUE TITLE
HTTPError - Garmin api problem?

### ISSUE THREAD

**Issue by fabxyz** [mkuthan/garmin-workouts#4]
I've got this connection error when using the tool as usual:

requests.exceptions.HTTPError: 402 Client Error: Payment Required for url: https://connect.garmin.com/modern/proxy/workout-service/workouts?start=0&limit=100
---
Traceback (most recent call last):
  File "C:/Users/Fabian/Documents/Git/garmin_workouts/garminworkouts/run_script_dbg.py", line 117, in <module>
    command_import(args)
  File "C:/Users/Fabian/Documents/Git/garmin_workouts/garminworkouts/run_script_dbg.py", line 21, in command_import
    existing_workouts_by_name = {Workout.extract_workout_name(w): w for w in connection.list_workouts()}
  File "C:/Users/Fabian/Documents/Git/garmin_workouts/garminworkouts/run_script_dbg.py", line 21, in <dictcomp>
    existing_workouts_by_name = {Workout.extract_workout_name(w): w for w in connection.list_workouts()}
  File "C:\Users\Fabian\Documents\Git\garmin_workouts\garminworkouts\garmin\garminclient.py", line 44, in list_workouts
    response.raise_for_status()
  File "C:\Users\Fabian\Documents\Git\garmin_workouts\py_env\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
    
   Is it possible that the Garmin api has changed? Has anyone encountered this problem already?

**Comment by mkuthan** [comment]
I'll look, mandatory headers have to be added to the requests. Perhaps trivial change.
